name: Publish Spatium Types

on:
  push:
    branches:
      - main
    paths:
      - 'packages/spatium-types/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Generate types
        run: node scripts/generate-types.mjs

      - name: Install & Build
        run: pnpm install && pnpm install discord.js && pnpm build
        working-directory: ./packages/spatium-types

      - name: Bump patch version
        run: npm version patch
        working-directory: ./packages/spatium-types

      - name: Publish to npm
        run: npm publish --access public
        working-directory: ./packages/spatium-types
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version changes
        run: |
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
